name: Script injection example
on:
   push:
      branches:
         - main
   issues:
      types:
         - opened
jobs:
   determine-issue:
      permissions:
         issues: write
      runs-on: ubuntu-latest
      env:
         AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      steps:
         - name: Dertirmine if issue is a bug
           run: |
              issue_title="${{ github.event.issue.title }}"
              if [[ "$issue_title" == *"bug"* ]]; then
              echo "Issue is about a bug!"
              else
              echo "Issue is not about a bug"
              fi
